### ISSUE TITLE
Error in Terraform script

### ISSUE THREAD

**Issue by tfo-inc** [transcelerate/ddf-sdr-platform#21]
Hello, we are trying to deploy Transcelerate to our own Azure Tenant.
During GitHub action deployment, we get the following error.
![image](https://user-images.githubusercontent.com/89004710/204805606-78b03d35-db10-409e-86e4-bfdc4a8e6f16.png)
Does someone have an idea what is wrong.

**Comment by sdr-support** [comment]
@tfo-inc 
Issues on this repository are not tracked. Common Support Request for all SDR Repos can be raised [here](https://github.com/transcelerate/ddf-sdr-support/issues/new/choose).
Please raise a new issue in the above mentioned link if you are still facing this error in deployment.
